# This file was generated by stellar_contract_bindings v0.5.0b0 and stellar_sdk v13.2.0.

from __future__ import annotations

from enum import IntEnum, Enum
from typing import Dict, List, Tuple, Optional, Union

from stellar_sdk import scval, xdr, Address, MuxedAccount, Keypair
from stellar_sdk.contract import AssembledTransaction, ContractClient

NULL_ACCOUNT = "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF"


class NameRecord:
    claimed_at: int
    name: bytes
    owner: Address
    public_key: bytes
    services: Dict[bytes, bytes]
    ttl: int
    tunnel_id: Address
    tunnel_relay: bytes
    version: int

    def __init__(
        self,
        claimed_at: int,
        name: bytes,
        owner: Union[Address, str],
        public_key: bytes,
        services: Dict[bytes, bytes],
        ttl: int,
        tunnel_id: Union[Address, str],
        tunnel_relay: bytes,
        version: int,
    ):
        self.claimed_at = claimed_at
        self.name = name
        self.owner = owner
        self.public_key = public_key
        self.services = services
        self.ttl = ttl
        self.tunnel_id = tunnel_id
        self.tunnel_relay = tunnel_relay
        self.version = version

    def to_scval(self) -> xdr.SCVal:
        return scval.to_struct(
            {
                "claimed_at": scval.to_uint64(self.claimed_at),
                "name": scval.to_string(self.name),
                "owner": scval.to_address(self.owner),
                "public_key": scval.to_bytes(self.public_key),
                "services": scval.to_map(
                    {
                        scval.to_string(k): scval.to_string(v)
                        for k, v in self.services.items()
                    }
                ),
                "ttl": scval.to_uint32(self.ttl),
                "tunnel_id": scval.to_address(self.tunnel_id),
                "tunnel_relay": scval.to_string(self.tunnel_relay),
                "version": scval.to_uint32(self.version),
            }
        )

    @classmethod
    def from_scval(cls, val: xdr.SCVal):
        elements = scval.from_struct(val)
        return cls(
            scval.from_uint64(elements["claimed_at"]),
            scval.from_string(elements["name"]),
            scval.from_address(elements["owner"]),
            scval.from_bytes(elements["public_key"]),
            {
                scval.from_string(k): scval.from_string(v)
                for k, v in scval.from_map(elements["services"]).items()
            },
            scval.from_uint32(elements["ttl"]),
            scval.from_address(elements["tunnel_id"]),
            scval.from_string(elements["tunnel_relay"]),
            scval.from_uint32(elements["version"]),
        )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, NameRecord):
            return NotImplemented
        return (
            self.claimed_at == other.claimed_at
            and self.name == other.name
            and self.owner == other.owner
            and self.public_key == other.public_key
            and self.services == other.services
            and self.ttl == other.ttl
            and self.tunnel_id == other.tunnel_id
            and self.tunnel_relay == other.tunnel_relay
            and self.version == other.version
        )

    def __hash__(self) -> int:
        return hash(
            (
                self.claimed_at,
                self.name,
                self.owner,
                self.public_key,
                self.services,
                self.ttl,
                self.tunnel_id,
                self.tunnel_relay,
                self.version,
            )
        )


class NameStatusKind(Enum):
    Active = "Active"
    Suspended = "Suspended"


class NameStatus:
    def __init__(
        self,
        kind: NameStatusKind,
    ):
        self.kind = kind

    def to_scval(self) -> xdr.SCVal:
        if self.kind == NameStatusKind.Active:
            return scval.to_enum(self.kind.name, None)
        if self.kind == NameStatusKind.Suspended:
            return scval.to_enum(self.kind.name, None)
        raise ValueError(f"Invalid kind: {self.kind}")

    @classmethod
    def from_scval(cls, val: xdr.SCVal):
        elements = scval.from_enum(val)
        kind = NameStatusKind(elements[0])
        if kind == NameStatusKind.Active:
            return cls(kind)
        if kind == NameStatusKind.Suspended:
            return cls(kind)
        raise ValueError(f"Invalid kind: {kind}")

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, NameStatus):
            return NotImplemented
        if self.kind != other.kind:
            return False
        return True

    def __hash__(self) -> int:
        return hash(self.kind)


class Client(ContractClient):
    def init(
        self,
        admin: Union[Address, str],
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[None]:
        return self.invoke(
            "init",
            [scval.to_address(admin)],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def claim(
        self,
        caller: Union[Address, str],
        name: bytes,
        tunnel_id: Union[Address, str],
        tunnel_relay: bytes,
        public_key: bytes,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[NameRecord]:
        """Claim a name in the HVYM namespace. Names are permanent -- there is
        no expiration. Reclamation is handled by cooperative governance
        via the revoke method."""
        return self.invoke(
            "claim",
            [
                scval.to_address(caller),
                scval.to_string(name),
                scval.to_address(tunnel_id),
                scval.to_string(tunnel_relay),
                scval.to_bytes(public_key),
            ],
            parse_result_xdr_fn=lambda v: NameRecord.from_scval(v),
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def revoke(
        self,
        caller: Union[Address, str],
        name: bytes,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[None]:
        """Suspend a name. Admin-only -- used for cooperative governance.
        A suspended name can be re-claimed by calling claim() again."""
        return self.invoke(
            "revoke",
            [scval.to_address(caller), scval.to_string(name)],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def resolve(
        self,
        name: bytes,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[Optional[NameRecord]]:
        """Look up a name. Read-only -- no gas cost via simulation."""
        return self.invoke(
            "resolve",
            [scval.to_string(name)],
            parse_result_xdr_fn=lambda v: (
                NameRecord.from_scval(v)
                if v.type != xdr.SCValType.SCV_VOID
                else scval.from_void(v)
            ),
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def transfer(
        self,
        caller: Union[Address, str],
        name: bytes,
        new_owner: Union[Address, str],
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[None]:
        """Transfer ownership to another address."""
        return self.invoke(
            "transfer",
            [
                scval.to_address(caller),
                scval.to_string(name),
                scval.to_address(new_owner),
            ],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def update_tunnel(
        self,
        caller: Union[Address, str],
        name: bytes,
        new_tunnel_id: Union[Address, str],
        new_tunnel_relay: bytes,
        new_public_key: bytes,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[None]:
        """Change the tunnel endpoint for a name."""
        return self.invoke(
            "update_tunnel",
            [
                scval.to_address(caller),
                scval.to_string(name),
                scval.to_address(new_tunnel_id),
                scval.to_string(new_tunnel_relay),
                scval.to_bytes(new_public_key),
            ],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def update_services(
        self,
        caller: Union[Address, str],
        name: bytes,
        services: Dict[bytes, bytes],
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[None]:
        """Update the service routing map (alice@gallery -> /gallery, etc.)."""
        return self.invoke(
            "update_services",
            [
                scval.to_address(caller),
                scval.to_string(name),
                scval.to_map(
                    {
                        scval.to_string(k): scval.to_string(v)
                        for k, v in services.items()
                    }
                ),
            ],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )
